### ISSUE TITLE
Feature-Request: possibility to include Mollie-script not on all pages

### ISSUE THREAD

**Issue by niklaswolf** [mollie/Shopware6Composables#4]
It would be very nice to be able to load the mollie script, which is loaded right now in the server plugin, not on every page.
For us, it only needs to be included on the checkout page where payment methods get selected by the user.

I see the following needs:
- be able to include the script from client side (not rely on the server plugin).
- maybe provide a way to trigger the script loading manually (which would check if the script is already loaded). This could actually be included in the client-plugin directly.

**Comment by niklaswolf** [comment]
@fjbender any chance that this can be included? :)

**Comment by fjbender** [comment]
Unfortunately, we're not ready to do additional changes to this package at the present time - mostly due to capacity constraints. I think the idea is good though and it's definitely high on the list of improvements I'd like to see here.
